### ISSUE TITLE
Обновление зависимостей пакета `@atls/typeorm-seeding`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/typeorm#7]
### С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

### Расскажите как вы это себе видите

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Исключения:
`typescript` обновлять не нужно.
`typeorm` оставить 2 минорную версию

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude пытаюсь обновить зависимости, ```yarn workspace <workspace> add <package@version>``` меняет package.json, но версия библиотеки подчеркнута вебштормом и при наведении говорит, что пакет не установлен. Yarn install так же не решает проблему. В корневом package.json тоже самое.

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov это какой именно пакет не обновляется? А при установке говорит что-нибудь? Напиши команду которой обновляешь

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude 
```artem@artem-To-be-filled-by-O-E-M:~/Dev/Atlantis/typeorm$ yarn workspace @atls/typeorm-seeding add faker@6.6.6
```
Вообще ни один пакет не устанавливается в этой репе.

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov А yarn.lock меняется?

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude да

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov Может дело в ide? Пробовал перезапускать? Или перезапустить typeorm engine

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude да уже даже ресетнулся. Может заклонилось криво. Как перезапустить typeorm engine?

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov ресета вебшторма должно быть достаточно. Там можно справа внизу на панели вроде нажать на тайпскрипт и перезапустить

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov я посмотрю тогда вечером сам

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude не могу решить проблему с тем, что пакеты не устанавливаются. Флаг -E не помогает. Так же билд не проходит даже без каких-либо изменений. Выдает:
<details> 

```shell
artem@artem-To-be-filled-by-O-E-M:~/Dev/Atlantis/typeorm$ yarn workspace @atls/typeorm-seeding run build
(node:19224) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/artem/Dev/Atlantis/typeorm/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:405:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:843:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}

Node.js v18.17.1
```

</details>

**Comment by ArtemMakhaydinov** [comment]
@SlumberyDude @TorinAsakura  не могу решить проблему с тем, что пакеты не устанавливаются. Флаг -E не помогает. Так же билд не проходит даже без каких-либо изменений. C репозиторием ```utils``` тоже самое. Билд выдает:
<details> 

```shell
artem@artem-To-be-filled-by-O-E-M:~/Dev/Atlantis/typeorm$ yarn workspace @atls/typeorm-seeding run build
(node:19224) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///home/artem/Dev/Atlantis/typeorm/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.
    at new NodeError (node:internal/errors:405:5)
    at ESMLoader.resolve (node:internal/modules/esm/loader:843:13)
    at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7) {
  code: 'ERR_LOADER_CHAIN_INCOMPLETE'
}

Node.js v18.17.1
```

</details>

**Comment by SlumberyDude** [comment]
@ArtemMakhaydinov Чет выглядит знакомо, думаю нужно обновить бандл ярна. Тот который тут сидит уже устарел.

Это можно сделать склонив себе репу `tools` и введя `yarn set version <путь к tools>/tools/yarn/cli/bundles/yarn.js`. Только не знаю, делать ли обновление в рамках этого таска или создавать отдельный.

**Comment by SlumberyDude** [comment]
@TorinAsakura Нужно обновить бандл ярна. Сделать таску?

**Comment by TorinAsakura** [comment]
Нет, это обычная процедура, такая же как yarn install

**Comment by TorinAsakura** [comment]
.

**Comment by Nelfimov** [comment]
Done https://github.com/atls/typeorm/pull/10
